// Generated by CoffeeScript 1.6.3
requirejs.config({
  baseUrl: 'js/compiled',
  paths: {
    jquery: ['http://code.jquery.com/jquery-1.10.2.min', '../jquery-1.10.2.min'],
    backbone: 'backbone.min',
    data: 'quiz-data',
    quiz: 'quiz',
    share: '../custom-share'
  }
});

requirejs(['jquery', 'backbone', 'data', 'quiz', 'share'], function($, _data, _quiz) {
  return $(function() {
    'use strict';
    _quiz.init(_data);
    _quiz.setIndex(0);
    return _quiz.run();
  });
});
