// Generated by CoffeeScript 1.6.3
define({
  index: -1,
  init: function(data) {
    this.data = data != null ? data : {};
    'use strict';
    this.maxIndex = this.data.pages.length;
    this.$quiz = $('.quiz');
    this.$quiz.removeClass('spinner');
    return this;
  },
  setIndex: function(index) {
    'use strict';
    var page;
    if (index === this.index || index < 0 || index > this.maxIndex) {
      return;
    }
    this.index = index;
    page = this.data.pages[index];
    return this.renderPage(page, !page.next, 100);
  },
  renderPage: function(page, isDone, animTime) {
    'use strict';
    var $answers, $question,
      _this = this;
    $question = this.$quiz.find('.question');
    $answers = this.$quiz.find('.answers');
    $question.fadeOut(animTime);
    return $answers.fadeOut(animTime, function() {
      var i, next, _i, _ref;
      $question.html('Level ' + page.level + ': ' + page.question).fadeIn(animTime);
      $answers.empty();
      for (i = _i = 0, _ref = page.answer.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        next = isDone ? -1 : page.next[i];
        _this.appendAnswer(page.answer[i], next, $answers);
      }
      return $answers.fadeIn(animTime, function() {
        if (isDone) {
          return alert('Quiz done !!!');
        }
      });
    });
  },
  appendAnswer: function(answer, next, $answers) {
    return $('<div class="answer">' + answer + '</div>').data('next', next).appendTo($answers);
  },
  run: function() {
    'use strict';
    var _this = this;
    this.$quiz.find('.answers').on('click', '.answer', function(e) {
      var next;
      next = parseInt($(e.target).data('next'));
      if (~next) {
        return _this.setIndex(next);
      } else {
        return console.log('!!!!!');
      }
    });
    return this;
  }
});
