// Generated by CoffeeScript 1.6.3
define({
  index: -1,
  init: function(data, number, $quiz) {
    this.data = data != null ? data : {};
    this.number = number != null ? number : 4;
    this.$quiz = $quiz != null ? $quiz : $('.quiz');
    'use strict';
    this.maxIndex = this.data.questions.length / this.number ^ 0;
    if (!(this.data.questions.length % this.number)) {
      this.maxIndex--;
    }
    this.$quiz.find('.questions').height(16 * this.number);
    return this;
  },
  renderPage: function(index) {
    'use strict';
    var $questions, n, x;
    if (index === this.index || index < 0 || index > this.maxIndex) {
      return;
    }
    this.index = index;
    x = this.index * this.number;
    n = this.number;
    $questions = this.$quiz.find('.questions');
    $questions.empty();
    while (x < this.data.questions.length && n--) {
      this.appendQuestion($questions, this.data.questions[x++]);
    }
    return this;
  },
  appendQuestion: function($questions, question) {
    return $('<div class="question"><li>' + question + '</li></div>').appendTo($questions);
  },
  renderFirstPage: function() {
    'use strict';
    return this.renderPage(0);
  },
  renderNextPage: function() {
    'use strict';
    return this.renderPage(this.index + 1);
  },
  renderPrevPage: function() {
    'use strict';
    return this.renderPage(this.index - 1);
  },
  run: function() {
    'use strict';
    var _this = this;
    this.$quiz.find('.arrow.prev').on('click', function() {
      return _this.renderPrevPage();
    });
    this.$quiz.find('.arrow.next').on('click', function() {
      return _this.renderNextPage();
    });
    return this;
  }
});
